version = 0.1
[default.deploy.parameters]
stack_name = "sf-agent"
resolve_s3 = true
s3_prefix = "sf-agent"
region = "ap-south-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "SFClientIDSecretName=\"sf_client_id\" WhatsappAPISecretName=\"WhatsAppAPIToken\" WhatsappNumberIDSecretname=\"WhatsappNumberID\" ApiGWKey=\"ApiGWKey\" ApiGWEndpoint=\"ApiGWEndpoint\""
image_repositories = []
